version: "3.8"

services:
  simulations-api:
    image: kmalski/simulations-api:latest
    container_name: simulations-api
    restart: on-failure
    networks:
      - simulations

  simulations-ui:
    image: kmalski/simulations-ui:latest
    container_name: simulations-ui
    restart: on-failure
    networks:
      - simulations

  swag:
    image: ghcr.io/linuxserver/swag:1.22.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - URL=simulations.malski.pl
      - VALIDATION=http
    volumes:
      - ./swag:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - simulations

networks:
  simulations:
    ipam:
      driver: default
      config:
        - subnet: 172.24.24.0/24
